name: Setup

inputs:
  python-version: 
    description: Python verion'
    required: true
    default: '3.10.12'

runs:
  using: composite
  steps:      
      - name: Set up Pyhton 3.10.12
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-verion }}
          cache: 'pip'
      
      - name: Install dependencies
        shell : bash
        run: |
          pip install fastapi locust pytest uvicorn coverage httpx pytest-mock pytest-profiling pylint sqlalchemy pydantic -r requirements.txt