name: Setup

inputs:
  python-version: 
    description: Python version'
    required: true
    default: '3.10.12'

runs:
  using: composite
  steps:
      - uses: actions/checkout@v4      
      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'
      
      - name: Install dependencies
        shell : bash
        run: |
          pip install fastapi locust pytest uvicorn coverage httpx pytest-mock pytest-profiling pylint sqlalchemy pydantic -r requirements.txt