name: Setup

inputs:
  python-version: 
    description: Python version ET installation des dépendances'
    required: true
    default: '3.10'

runs:
  using: composite
  steps:     
      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'
      
      - name: Install dependencies
        shell : bash
        run: |
          pip install pytest pytest-profiling selenium webdriver-manager
