name : Build and execute Python script

on:
  push:
    branches:
      - main


jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Composite Action
        uses: ./.github/actions/setup
        with:
         python-version: ${{ matrix.python-version }}
     
      
      - name: Run Exo1
        run: python main.py 

      - name: Upload screenshot artifact
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshot_before_click.png

      - name: Discord notification
        env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
            DISCORD_USERNAME: Caro-Quentin-Lucas
        uses: Ilshidur/action-discord@master
        with:
         args: 'Les tests ont été effectué avec succès.'
  
  release: 
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/main'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
    steps:
      - name: Release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: major
          use_github_release_notes: true

    