name : Build and execute Python script

on:
  push:
    branches:
      - main


jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Composite Action
        uses: ./.github/actions/setup
        with:
         python-version: ${{ matrix.python-version }}
     
      - name: Run Ex02
        run: python exo2.py

      - name: Run exo1
        run: python exo1.py 

      - name: Pytest Exo2
        run: pytest pytest_exo2.py

     


      
  release: 
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
    steps:      
      - name: Create Release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: major
          use_github_release_notes: true

    